### ISSUE TITLE
Did moving to cpp speed up?

### ISSUE THREAD

**Issue by 5nizza** [gaperez64/AbsSynthe#1]
hi Gulermo, you have two branches: python and cpp version. 
Do you know if moving from python to cpp helped? 
(apart from having the latest version of CUDD)

[label:question]

**Comment by gaperez64** [comment]
Hello. The cpp version is a lot faster, I think partly because you can release some BDDs you no longer need manually in cpp while in the python implementation this was up to the garbage collector + CUDD wrapper. We had speed-ups from 2x to even 5x sometimes, so yes, it did help a lot.
